server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /app-authors/ {
        proxy_pass http://authors-app/;
    }

    location /app-books/ {
        proxy_pass http://books-app/;
    }
}